version: "3.8"

services:
  nginx:
    build:
      # Nginx serves static files, which includes the JavaScript client
      context: ./client

  redis:
    image: redis:6

  nodejs-app:
    build:
      context: ./server
