version: "3.8"

services:
  proxy:
    ports:
      - 8080:80

  server:
    build:
      target: dev
    volumes:
      - ./server/src:/home/node/app/src
      - ./server/package.json:/home/node/app/package.json
      - ./server/package-lock.json:/home/node/app/package-lock.json
      - ./server/tsconfig.json:/home/node/app/tsconfig.json
    ports:
      - 3000:3000
